/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.70
 * Generated at: 2017-02-18 19:57:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title></title>\r\n");
      out.write("<meta name=\"keywords\" content=\"\" />\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<link href=\"http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"css/default.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<link href=\"css/fonts.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("\r\n");
      out.write("<!--[if IE 6]><link href=\"default_ie6.css\" rel=\"stylesheet\" type=\"text/css\" /><![endif]-->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"header-wrapper\">\r\n");
      out.write("\t<div id=\"header\" class=\"container\">\r\n");
      out.write("\t\t<div id=\"logo\">\r\n");
      out.write("\t\t\t<h1><a href=\"#\">HOME SERVICES</a></h1>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"menu\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li class=\"active\"><a href=\"#\" accesskey=\"1\" title=\"\">Homepage</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"bpoLogin.html \" accesskey=\"2\" title=\"\">BPO</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"admin.html\" accesskey=\"3\" title=\"\">Login As Admin</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"userlogin.html\" accesskey=\"4\" title=\"\">Login As User</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\" accesskey=\"5\" title=\"\">Contact Us</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"wrapper\">\r\n");
      out.write("\t<div id=\"staff\" class=\"container\">\r\n");
      out.write("\t\t<div class=\"title\">\r\n");
      out.write("\t\t\t<h2>Who Are WE</h2>\r\n");
      out.write("\t\t\t<span>Donec leo, vivamus fermentum nibh in augue praesent a lacus at urna congue rutrum</span> </div>\r\n");
      out.write("\t\t<div class=\"boxA\"><img src=\"images/pic01.jpg\" width=\"300\" height=\"450\" alt=\"\" /></div>\r\n");
      out.write("\t\t<div class=\"boxB\"><img src=\"images/pic02.jpg\" width=\"300\" height=\"450\" alt=\"\" /></div>\r\n");
      out.write("\t\t<div class=\"boxC\"><img src=\"images/pic03.jpg\" width=\"300\" height=\"450\" alt=\"\" /></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"page\" class=\"container\">\r\n");
      out.write("\t\t<div class=\"boxA\">\r\n");
      out.write("\t\t\t<h2>Fusce ultrices<br />\r\n");
      out.write("\t\t\t\t<span>fringilla metus</span></h2>\r\n");
      out.write("\t\t\t<p>Donec leo, vivamus fermentum nibh in augue praesent a lacus at urna congue rutrum.</p>\r\n");
      out.write("\t\t\t<ul class=\"style4\">\r\n");
      out.write("\t\t\t\t<li class=\"first\"><a href=\"#\">Consectetuer adipiscing elit</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">Metus aliquam pellentesque</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">Proin gravida orci porttitor</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"boxB\">\r\n");
      out.write("\t\t\t<h2>Praesent<br />\r\n");
      out.write("\t\t\t\t<span> scelerisque scelerisque</span></h2>\r\n");
      out.write("\t\t\t<ul class=\"style3\">\r\n");
      out.write("\t\t\t\t<li class=\"first\">\r\n");
      out.write("\t\t\t\t\t<p class=\"date\"><a href=\"#\">Jan<b>30</b></a></p>\r\n");
      out.write("\t\t\t\t\t<h3>Amet sed volutpat mauris</h3>\r\n");
      out.write("\t\t\t\t\t<p><a href=\"#\">Mauris tempus nibh sodales adipiscing dolore.</a></p>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<p class=\"date\"><a href=\"#\">Jan<b>28</b></a></p>\r\n");
      out.write("\t\t\t\t\t<h3>Sagittis diam dolor amet</h3>\r\n");
      out.write("\t\t\t\t\t<p><a href=\"#\">Duis arcu tortor fringilla sed  sed magna.</a></p>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"boxC\">\r\n");
      out.write("\t\t\t<h2>Etiam posuere<br />\r\n");
      out.write("\t\t\t\t<span>augue sit amet</span></h2>\r\n");
      out.write("\t\t\t<ul class=\"style4\">\r\n");
      out.write("\t\t\t\t<li class=\"first\"><a href=\"#\">Consectetuer adipiscing elit</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">Metus aliquam pellentesque</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">Suspendisse iaculis mauris</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">Urnanet non molestie semper</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">Suspendisse iaculis mauris</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"welcome-wrapper\">\r\n");
      out.write("\t<div id=\"welcome\" class=\"container\">\r\n");
      out.write("\t\t<div class=\"title\">\r\n");
      out.write("\t\t\t<h2>Welcome to our website</h2>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<p>This is <strong>OpenSpace</strong>, a free, fully standards-compliant CSS template designed by <a href=\"http://templated.co\" rel=\"nofollow\">TEMPLATED</a>. The photos in this template are from <a href=\"http://fotogrph.com/\"> Fotogrph</a>. This free template is released under the <a href=\"http://templated.co/license\">Creative Commons Attribution</a> license, so you're pretty much free to do whatever you want with it (even use it commercially) provided you give us credit for it. Have fun :) </p>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"copyright\" class=\"container\">\r\n");
      out.write("\t<p>&copy; Untitled. All rights reserved. | Photos by <a href=\"http://fotogrph.com/\">Fotogrph</a> | Design by <a href=\"http://templated.co\" rel=\"nofollow\">TEMPLATED</a>.</p>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
